# Imagen
FROM python:3 

# Directorio dentro de la imagen
WORKDIR /usr/src/app

# Copiar holamundo.py al directorio dentro de la imagen
COPY holamundo.py ./

# Ejecutar el siguiente comando
CMD [ "python", "./holamundo.py" ]